service:
  name: whale-analysis

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    WHALE_ALERT_IO_API_KEY: ${ssm:WHALE_ALERT_IO_API_KEY}

functions:
  index:
    handler: src/handlers/index-handler.get
    events:
      - http:
          method: get
          path: /
